version: "1.0"
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: prueba_tecnica-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - prueba_tecnica
  app:
    build:
      args:
        user: imera92
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: prueba_tecnica
    container_name: prueba_tecnica-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - prueba_tecnica
  db:
    image: mysql:8.0
    container_name: prueba_tecnica-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - prueba_tecnica

networks:
  prueba_tecnica:
    driver: bridge